<a href="https://colab.research.google.com/github/esa-prakasa/PyTorchForBeginner/blob/master/pyTorch_MatrixOperationUsingGPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create two array of data (x and y). The y arry is obtained from equation y=2x+1.

*Kode digunakan untuk membuat dua matriks x dan y. Matriks y diperoleh dengan menggunakan persamaan y=2x+1*

In [9]:
import torch
x = 10*torch.rand(20)
y = 2*x + 1
print(x)
print(y)

tensor([2.5511, 3.6788, 6.4509, 0.2797, 2.3836, 2.4070, 0.0250, 1.9105, 6.6110,
        8.1948, 8.5987, 9.8416, 2.6046, 9.1500, 3.7221, 1.8485, 3.0257, 3.5366,
        2.8014, 3.5286])
tensor([ 6.1023,  8.3576, 13.9018,  1.5593,  5.7671,  5.8139,  1.0499,  4.8210,
        14.2220, 17.3896, 18.1975, 20.6833,  6.2091, 19.2999,  8.4443,  4.6970,
         7.0515,  8.0731,  6.6029,  8.0571])


Create two matrices a and b. Both matrices, c and d are obtained by adding a to b. But, two different methods used in additional operation.

*Matriks a dan b dibuat dengan menggunakan pembangkit bilangan random. Matriks c dan d adalah hasil jumlahan antara matriks a dan b, namun menggunakan cara yang berbeda. Cara pertama dengan penjumlahan biasa, cara kedua dengan menggunakan fungsi add() pada PyTorch.*

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a+b
d = torch.add(a,b)

print(c)
print(d)

tensor([[1.4288, 1.4615],
        [0.7371, 0.9043]])
tensor([[1.4288, 1.4615],
        [0.7371, 0.9043]])


This is part is comparison between using non-GPU and GPU. Implementation of code using GPU can speed up computation time up to 15x faster!

Bagian ini menunjukkan perbandingan antara penggunaan non-GPU dan GPU. Implementasi kode program dengan menggunakan GPU dapat mempercepat komputasi hingga 15x lebih cepat.

In [9]:
import torch
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

start.record()
N = 10000
a = torch.rand(N,N)
b = torch.rand(N,N)
e = a.matmul(b)
end.record()

torch.cuda.synchronize()

compTime = start.elapsed_time(end)
compTime = compTime/1000 
print("Computation Time is "+str(compTime)+" second")
## Computation Time is 29.04316015625 second

Computation Time is 29.04316015625 second


In [11]:
import torch
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

start.record()
N = 10000
a = torch.rand(N,N)
b = torch.rand(N,N)
a = a.cuda()
b = b.cuda()
e = a.matmul(b)
end.record()

torch.cuda.synchronize()

compTime = start.elapsed_time(end)
compTime = compTime/1000 
print("Computation Time is "+str(compTime)+" second")
## Computation Time is 2.57491943359375 second

Computation Time is 2.51195166015625 second
