<a href="https://colab.research.google.com/github/esa-prakasa/PyTorchForBeginner/blob/master/pyTorch_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create two array of data (x and y). The y arry is obtained from equation y=2x+1.

In [9]:
import torch
x = 10*torch.rand(20)
y = 2*x + 1
print(x)
print(y)

tensor([2.5511, 3.6788, 6.4509, 0.2797, 2.3836, 2.4070, 0.0250, 1.9105, 6.6110,
        8.1948, 8.5987, 9.8416, 2.6046, 9.1500, 3.7221, 1.8485, 3.0257, 3.5366,
        2.8014, 3.5286])
tensor([ 6.1023,  8.3576, 13.9018,  1.5593,  5.7671,  5.8139,  1.0499,  4.8210,
        14.2220, 17.3896, 18.1975, 20.6833,  6.2091, 19.2999,  8.4443,  4.6970,
         7.0515,  8.0731,  6.6029,  8.0571])


Create two matrices a and b. Both matrices, c and d are obtained by adding a to b. But, two different methods used in additional operation.

In [13]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = a+b
d = torch.add(a,b)

print(c)
print(d)

tensor([[1.4288, 1.4615],
        [0.7371, 0.9043]])
tensor([[1.4288, 1.4615],
        [0.7371, 0.9043]])
