<a href="https://colab.research.google.com/github/esa-prakasa/PyTorchForBeginner/blob/master/pyTorch_learnTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch

x = torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
y = torch.tensor([0.1, 0.2, 0.3],dtype = torch.float64)
print(x)
print(y)

z = torch.zeros(5,1)
a = torch.ones(1,5)
print(z)
print(a)

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])
tensor([0.1000, 0.2000, 0.3000], dtype=torch.float64)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[1., 1., 1., 1., 1.]])


These instructions are used to generate a 3x3 random numbers. By applying max() function to the generated tensor b, we can get the maximum value of 3x3 random numbers. The maximum number is stored as bMax variable. However, the variable type is still as tensor format. To extract its real value, we use item() function. Finally, a single number can be extracted from the tensor format.

In [0]:
b = torch.rand(3,3)
print(b)

bMax = b.max()

print(bMax.item())
