<a href="https://colab.research.google.com/github/esa-prakasa/PyTorchForBeginner/blob/master/torch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
a = torch.tensor(3)
print("A scalar value: ")
print(a)

print("An array: ")
b = torch.tensor([1, 2])
print(b)

print("A matrix: ")
c = torch.zeros([2, 2])
print(c)

print("A random matrix")
d = torch.rand([2, 2])
print(d)

A scalar value: 
tensor(3)
An array: 
tensor([1, 2])
A matrix: 
tensor([[0., 0.],
        [0., 0.]])
A random matrix
tensor([[0.4290, 0.9535],
        [0.5621, 0.1437]])


In [25]:
x = torch.randn([3, 5])
y = torch.randn([5, 4])

print(x)
print(y)

z = x @ y

print(z)

x = torch.randn([3, 3])
y = torch.randn([3, 3])
z = x + y
print(z)

print("Covert from tensor to numpy")
zNump = z.numpy()
print(zNump)

print("Row 0 to 2, column 0")
print(zNump[0:3,0])

tensor([[-0.4304, -0.1643,  1.0647,  0.6224,  0.4378],
        [ 0.4151,  2.3563,  0.7522,  0.5613, -1.5655],
        [ 0.5611, -0.0725, -1.1340, -1.1584, -0.7256]])
tensor([[ 0.9487,  0.7186,  0.9243,  0.4274],
        [ 0.2468, -0.2030, -0.1295,  1.8800],
        [ 1.0230,  2.0493,  0.7550, -1.8731],
        [-0.5277,  0.1193,  1.2613, -0.5715],
        [ 0.3041,  1.0269, -1.9228,  0.4014]])
tensor([[ 0.4450,  2.4298,  0.3704, -2.6670],
        [ 0.9723, -0.1792,  4.3647,  2.2491],
        [-0.2550, -2.7894, -0.3939,  2.5984]])
tensor([[ 0.0894, -0.9542,  0.4983],
        [ 0.5686,  1.3331, -2.4392],
        [ 0.2206,  0.6598,  1.8495]])
Covert from tensor to numpy
[[ 0.08939701 -0.95417476  0.4982791 ]
 [ 0.5685613   1.3330753  -2.439239  ]
 [ 0.22058564  0.6598427   1.8494606 ]]
Row 0 to 2, column 0
[0.08939701 0.5685613  0.22058564]
